const PDFDocument = require('pdfkit');

// Color palette for consistent styling across all PDFs
const colors = {
  primary: '#1E40AF',      // Deep blue
  secondary: '#3B82F6',    // Blue
  accent: '#8B5CF6',       // Purple
  success: '#10B981',      // Green
  warning: '#F59E0B',      // Orange
  danger: '#EF4444',       // Red
  light: '#F8FAFC',        // Light gray
  dark: '#1F2937',         // Dark gray
  white: '#FFFFFF',
  // Grade colors
  gradeA: '#10B981',       // Green for A+/A
  gradeB: '#3B82F6',       // Blue for B+/B
  gradeC: '#F59E0B',       // Orange for C
  gradeF: '#EF4444'        // Red for F
};

// Helper function to draw gradient background
const drawGradientRect = (doc, x, y, width, height, color1, color2) => {
  const gradient = doc.linearGradient(x, y, x, y + height);
  gradient.stop(0, color1).stop(1, color2);
  doc.rect(x, y, width, height).fill(gradient);
};

// Helper function to create professional header
const createProfessionalHeader = (doc, title, subtitle = null) => {
  const pageWidth = doc.page.width;
  
  // Header with gradient background
  drawGradientRect(doc, 0, 0, pageWidth, 120, colors.primary, colors.secondary);

  // EDUTRACK Title
  doc.fontSize(28)
     .fillColor(colors.white)
     .font('Helvetica-Bold')
     .text('EDUTRACK', 0, 25, { align: 'center' });

  // Subtitle
  doc.fontSize(16)
     .fillColor(colors.light)
     .font('Helvetica')
     .text('Educational Management System', 0, 60, { align: 'center' });

  // Document title with decorative border
  if (title) {
    doc.rect(40, 140, pageWidth - 80, 60)
       .fillAndStroke(colors.accent, colors.primary);
    
    doc.fontSize(20)
       .fillColor(colors.white)
       .font('Helvetica-Bold')
       .text(title.toUpperCase(), 0, 160, { align: 'center' });
  }

  return 220; // Return Y position after header
};

// Helper function to create professional footer
const createProfessionalFooter = (doc, customText = null) => {
  const pageWidth = doc.page.width;
  const pageHeight = doc.page.height;
  const footerY = pageHeight - 60;
  
  drawGradientRect(doc, 0, footerY, pageWidth, 60, colors.dark, colors.primary);
  
  doc.fontSize(10)
     .fillColor(colors.white)
     .font('Helvetica')
     .text(customText || 'Generated by EDUTRACK - Educational Management System', 0, footerY + 20, { align: 'center' })
     .text(`Report generated on ${new Date().toLocaleString()}`, 0, footerY + 35, { align: 'center' });
};

// Helper function to create information box
const createInfoBox = (doc, x, y, width, height, data) => {
  doc.rect(x, y, width, height)
     .fillAndStroke(colors.light, colors.secondary);

  let currentY = y + 15;
  Object.entries(data).forEach(([key, value]) => {
    doc.fontSize(12)
       .fillColor(colors.dark)
       .font('Helvetica-Bold')
       .text(`${key}: `, x + 20, currentY);
    
    doc.font('Helvetica')
       .text(value, x + 100, currentY);
    
    currentY += 20;
  });
};

// Helper function to create colorful table
const createColorfulTable = (doc, headers, data, startY, options = {}) => {
  const {
    tableLeft = 40,
    rowHeight = 25,
    colWidths = null,
    gradeColumn = null,
    totalColumn = null
  } = options;

  const pageWidth = doc.page.width;
  const defaultColWidth = (pageWidth - 2 * tableLeft) / headers.length;
  const actualColWidths = colWidths || headers.map(() => defaultColWidth);
  
  let currentY = startY;
  let currentX = tableLeft;

  // Calculate column positions
  const colPositions = [tableLeft];
  for (let i = 1; i < actualColWidths.length; i++) {
    colPositions[i] = colPositions[i-1] + actualColWidths[i-1];
  }
  const totalTableWidth = colPositions[colPositions.length - 1] + actualColWidths[actualColWidths.length - 1] - tableLeft;

  // Header background
  drawGradientRect(doc, tableLeft, currentY - 6, totalTableWidth, rowHeight, colors.primary, colors.secondary);

  // Header text
  currentX = tableLeft;
  headers.forEach((header, i) => {
    doc.fontSize(10)
       .fillColor(colors.white)
       .font('Helvetica-Bold')
       .text(header, colPositions[i] + 5, currentY + 8, { 
         width: actualColWidths[i] - 10, 
         align: 'center' 
       });
  });

  currentY += rowHeight;

  // Data rows with alternating colors
  data.forEach((row, index) => {
    // Alternating row colors
    const bgColor = index % 2 === 0 ? colors.white : colors.light;
    doc.rect(tableLeft, currentY, totalTableWidth, rowHeight)
       .fill(bgColor)
       .stroke(colors.secondary);

    // Row data
    row.forEach((cellData, i) => {
      let textColor = colors.dark;
      let cellBgColor = null;

      // Special formatting for grade column
      if (gradeColumn === i) {
        const grade = cellData.toString().toUpperCase();
        if (grade.includes('A')) {
          textColor = colors.gradeA;
          cellBgColor = '#ECFDF5'; // Light green
        } else if (grade.includes('B')) {
          textColor = colors.gradeB;
          cellBgColor = '#EFF6FF'; // Light blue
        } else if (grade.includes('C')) {
          textColor = colors.warning;
          cellBgColor = '#FEF3C7'; // Light yellow
        } else if (grade.includes('F')) {
          textColor = colors.gradeF;
          cellBgColor = '#FEF2F2'; // Light red
        }
      }

      // Special formatting for total column
      if (totalColumn === i) {
        const total = parseInt(cellData) || 0;
        if (total >= 55) {
          textColor = colors.gradeA;
          cellBgColor = '#ECFDF5';
        } else if (total >= 45) {
          textColor = colors.gradeB;
          cellBgColor = '#EFF6FF';
        } else if (total >= 36) {
          textColor = colors.warning;
          cellBgColor = '#FEF3C7';
        } else {
          textColor = colors.gradeF;
          cellBgColor = '#FEF2F2';
        }
      }

      // Apply cell background if specified
      if (cellBgColor) {
        doc.rect(colPositions[i], currentY, actualColWidths[i], rowHeight)
           .fill(cellBgColor);
      }

      doc.fontSize(9)
         .fillColor(textColor)
         .font('Helvetica')
         .text(cellData.toString(), colPositions[i] + 5, currentY + 8, { 
           width: actualColWidths[i] - 10, 
           align: i === 0 ? 'left' : 'center' 
         });
    });

    currentY += rowHeight;
  });

  // Table border
  doc.rect(tableLeft, startY - 6, totalTableWidth, (data.length + 1) * rowHeight)
     .stroke(colors.primary);

  return currentY;
};

// Helper function to create statistics boxes
const createStatisticsBoxes = (doc, stats, startY) => {
  const pageWidth = doc.page.width;
  const boxWidth = 150;
  const boxHeight = 60;
  const spacing = 20;
  const totalWidth = stats.length * boxWidth + (stats.length - 1) * spacing;
  const startX = (pageWidth - totalWidth) / 2;

  stats.forEach((stat, i) => {
    const boxX = startX + i * (boxWidth + spacing);
    
    // Stat box with gradient
    drawGradientRect(doc, boxX, startY, boxWidth, boxHeight, stat.color || colors.primary, colors.secondary);

    doc.fontSize(10)
       .fillColor(colors.white)
       .font('Helvetica')
       .text(stat.label, boxX + 10, startY + 15, { width: boxWidth - 20, align: 'center' });

    doc.fontSize(16)
       .fillColor(colors.white)
       .font('Helvetica-Bold')
       .text(stat.value.toString(), boxX + 10, startY + 30, { width: boxWidth - 20, align: 'center' });
  });

  return startY + boxHeight + 20;
};

// Main PDF generation functions for different document types

// 1. Student Report PDF - Simplified version
const generateStudentReportPDF = (res, student, subjects, filename) => {
  try {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=${filename}`);
    doc.pipe(res);

    // Simple header
    drawGradientRect(doc, 0, 0, doc.page.width, 80, colors.primary, colors.secondary);
    
    doc.fontSize(24)
       .fillColor(colors.white)
       .font('Helvetica-Bold')
       .text('EDUTRACK', 0, 25, { align: 'center' });
    
    // Determine subtitle based on number of subjects
    let subtitle;
    if (!subjects || subjects.length === 0) {
      subtitle = 'Internal Marks Report';
    } else if (subjects.length === 1) {
      subtitle = `${subjects[0].paper} - Internal Marks Report`;
    } else {
      subtitle = 'All Papers - Internal Marks Report';
    }
    
    doc.fontSize(12)
       .fillColor(colors.light)
       .font('Helvetica')
       .text(subtitle, 0, 50, { align: 'center' });

    // Student info
    let currentY = 100;
    doc.fontSize(16)
       .fillColor(colors.dark)
       .font('Helvetica-Bold')
       .text(`${student.name}`, 50, currentY);

    doc.fontSize(12)
       .fillColor(colors.dark)
       .font('Helvetica')
       .text(`Roll No: ${student.rollNo}`, 50, currentY + 20)
       .text(`Section: ${student.section}`, 50, currentY + 35)
       .text(`Department: ${student.course || student.department}`, 50, currentY + 50);

    currentY += 75;

    // Use actual subjects data only - no sample data fallback
    let displaySubjects = subjects || [];

    // Enhanced subjects table with better spacing
    if (true) { // Force table generation for debugging
      doc.fontSize(14)
         .fillColor(colors.primary)
         .font('Helvetica-Bold')
         .text('ACADEMIC PERFORMANCE', 50, currentY);

      currentY += 30;

      // Calculate available space and adjust row height accordingly
      const availableHeight = doc.page.height - currentY - 80; // Reserve minimal space for summary and footer
      const dataToShow = displaySubjects.length > 0 ? displaySubjects : [
        {
          paper: 'No Data Available',
          subject: 'No Data Available', 
          marks: { midMarks: 0, lab: 0, assignmentQuiz: 0, attendance: 0, total: 0 }
        }
      ];
      
      const headerHeight = 25;
      const summaryHeight = 50;
      const tableDataHeight = availableHeight - headerHeight - summaryHeight;
      const rowHeight = Math.max(18, Math.min(22, Math.floor(tableDataHeight / dataToShow.length))); // Minimum 18px, maximum 22px per row

      // Enhanced table headers - centered on page with wider Subject column
      const headerY = currentY;
      const colWidths = [140, 60, 60, 70, 70, 70, 50]; // Increased Subject column from 100 to 140
      const tableWidth = colWidths.reduce((sum, width) => sum + width, 0); // 520px
      const pageWidth = doc.page.width; // 595px for A4
      const leftMargin = (pageWidth - tableWidth) / 2; // Center the table
      let colX = leftMargin;
      
      // Header background with gradient effect - centered
      doc.rect(leftMargin, headerY, tableWidth, headerHeight)
         .fillAndStroke('#1E40AF', '#000000');
      
      // Header text with better positioning
      doc.fontSize(10)
         .fillColor('#FFFFFF')
         .font('Helvetica-Bold');
      
      const headers = ['Subject', 'Mid (30)', 'Lab (10)', 'Assign (10)', 'Attend (10)', 'Total (60)', 'Grade'];
      headers.forEach((header, i) => {
        const textY = headerY + Math.floor((headerHeight - 10) / 2);
        doc.text(header, colX + 5, textY, { width: colWidths[i] - 10, align: 'center' });
        
        // Draw vertical lines between header columns
        if (i < headers.length - 1) {
          doc.moveTo(colX + colWidths[i], headerY)
             .lineTo(colX + colWidths[i], headerY + headerHeight)
             .stroke('#FFFFFF');
        }
        
        colX += colWidths[i];
      });
      
      currentY += headerHeight;
      
      // Enhanced data rows with better spacing
      dataToShow.forEach((subject, index) => {
        const marks = subject.marks || subject;
        const total = marks.total || 0;
        const grade = calculateGrade(total);
        const percentage = ((total / 60) * 100).toFixed(1);
        
        // Alternating row colors with better contrast - centered
        const bgColor = index % 2 === 0 ? '#FFFFFF' : '#F8FAFC';
        doc.rect(leftMargin, currentY, tableWidth, rowHeight)
           .fillAndStroke(bgColor, '#E5E7EB');
        
        // Enhanced data text with better positioning
        doc.fontSize(9)
           .fillColor('#000000')
           .font('Helvetica');
        
        const rowData = [
          subject.paper || subject.subject || 'N/A',
          (marks.midMarks || 0).toString(),
          (marks.lab || 0).toString(),
          (marks.assignmentQuiz || 0).toString(),
          (marks.attendance || 0).toString(),
          total.toString(),
          grade
        ];
        
        colX = leftMargin;
        const textY = currentY + Math.floor((rowHeight - 9) / 2);
        
        rowData.forEach((data, i) => {
          // Special handling for Subject column (index 0) - wrap long text
          if (i === 0) {
            const subjectText = data.toString();
            if (subjectText.length > 20) {
              // Split long subject names into multiple lines
              const words = subjectText.split(' ');
              let line1 = '';
              let line2 = '';
              
              // Try to split at a reasonable point
              const midPoint = Math.ceil(words.length / 2);
              line1 = words.slice(0, midPoint).join(' ');
              line2 = words.slice(midPoint).join(' ');
              
              doc.text(line1, colX + 5, textY - 3, { width: colWidths[i] - 10, align: 'left' });
              if (line2) {
                doc.text(line2, colX + 5, textY + 6, { width: colWidths[i] - 10, align: 'left' });
              }
            } else {
              doc.text(data, colX + 5, textY, { width: colWidths[i] - 10, align: 'left' });
            }
          }
          // Enhanced color-coding for grade column
          else if (i === 6) { // Grade column
            // Draw background first, then set text color with better contrast
            if (grade.includes('A')) {
              doc.rect(colX + 2, currentY + 2, colWidths[i] - 4, rowHeight - 4)
                 .fill('#ECFDF5');
              doc.fillColor('#065F46'); // Darker green for better contrast
            } else if (grade.includes('B')) {
              doc.rect(colX + 2, currentY + 2, colWidths[i] - 4, rowHeight - 4)
                 .fill('#EFF6FF');
              doc.fillColor('#1E40AF'); // Darker blue for better contrast
            } else if (grade.includes('C')) {
              doc.rect(colX + 2, currentY + 2, colWidths[i] - 4, rowHeight - 4)
                 .fill('#FEF3C7');
              doc.fillColor('#D97706'); // Darker orange for better contrast
            } else if (grade.includes('F')) {
              doc.rect(colX + 2, currentY + 2, colWidths[i] - 4, rowHeight - 4)
                 .fill('#FEF2F2');
              doc.fillColor('#DC2626'); // Darker red for better contrast
            } else {
              doc.fillColor('#000000'); // Default black text
            }
            doc.font('Helvetica-Bold');
            doc.text(data, colX + 5, textY, { width: colWidths[i] - 10, align: 'center' });
          } else if (i === 5) { // Total column
            doc.fillColor('#000000').font('Helvetica-Bold');
            doc.text(data, colX + 5, textY, { width: colWidths[i] - 10, align: 'center' });
          } else {
            doc.fillColor('#000000').font('Helvetica');
            doc.text(data, colX + 5, textY, { width: colWidths[i] - 10, align: 'center' });
          }
          
          // Draw vertical lines between columns
          if (i < rowData.length - 1) {
            doc.moveTo(colX + colWidths[i], currentY)
               .lineTo(colX + colWidths[i], currentY + rowHeight)
               .stroke('#E5E7EB');
          }
          
          colX += colWidths[i];
        });
        
        // Draw horizontal line after each row - centered
        doc.moveTo(leftMargin, currentY + rowHeight)
           .lineTo(leftMargin + tableWidth, currentY + rowHeight)
           .stroke('#E5E7EB');
        
        currentY += rowHeight;
      });
      
      // Enhanced table border - centered
      doc.rect(leftMargin, headerY, tableWidth, headerHeight + (dataToShow.length * rowHeight))
         .stroke('#1E40AF');
      
      currentY += 15;

      // Enhanced overall performance summary with better layout
      const totalMarks = displaySubjects.reduce((sum, s) => sum + ((s.marks?.total || s.total) || 0), 0);
      const avgMarks = displaySubjects.length > 0 ? totalMarks / displaySubjects.length : 0;
      const overallGrade = calculateGrade(avgMarks);
      const passCount = displaySubjects.filter(s => ((s.marks?.total || s.total) || 0) >= 36).length;
      const avgPercentage = ((avgMarks / 60) * 100).toFixed(1);
      const passRate = displaySubjects.length > 0 ? ((passCount / displaySubjects.length) * 100).toFixed(1) : 0;

      // Compact performance summary box - centered
      doc.rect(leftMargin, currentY, tableWidth, 60)
         .fillAndStroke(colors.accent, colors.primary);

      doc.fontSize(12)
         .fillColor(colors.white)
         .font('Helvetica-Bold')
         .text('OVERALL PERFORMANCE SUMMARY', leftMargin + 10, currentY + 10);

      // Performance metrics in compact layout
      doc.fontSize(10)
         .fillColor(colors.white)
         .font('Helvetica')
         .text(`Subjects: ${displaySubjects.length} | Passed: ${passCount} | Pass Rate: ${passRate}%`, leftMargin + 10, currentY + 30)
         .text(`Average: ${avgMarks.toFixed(1)}/60 (${avgPercentage}%) | Grade: ${overallGrade}`, leftMargin + 10, currentY + 45);

      // Compact performance status indicator
      let statusText = 'EXCELLENT';
      let statusColor = colors.success;
      if (avgMarks < 36) {
        statusText = 'NEEDS IMPROVEMENT';
        statusColor = colors.danger;
      } else if (avgMarks < 45) {
        statusText = 'SATISFACTORY';
        statusColor = colors.warning;
      } else if (avgMarks < 55) {
        statusText = 'GOOD';
        statusColor = colors.secondary;
      }

      doc.rect(leftMargin + 400, currentY + 20, 120, 30)
         .fillAndStroke(statusColor, colors.white);

      doc.fontSize(9)
         .fillColor(colors.white)
         .font('Helvetica-Bold')
         .text(statusText, leftMargin + 410, currentY + 30, { width: 100, align: 'center' });

      currentY += 70;

      // Compact grade distribution (if multiple subjects)
      if (displaySubjects.length > 1) {
        const gradeDistribution = {
          'A+/A': displaySubjects.filter(s => ((s.marks?.total || s.total) || 0) >= 50).length,
          'B+/B': displaySubjects.filter(s => {
            const total = (s.marks?.total || s.total) || 0;
            return total >= 40 && total < 50;
          }).length,
          'C': displaySubjects.filter(s => {
            const total = (s.marks?.total || s.total) || 0;
            return total >= 36 && total < 40;
          }).length,
          'F': displaySubjects.filter(s => ((s.marks?.total || s.total) || 0) < 36).length
        };

        doc.rect(leftMargin, currentY, tableWidth, 30)
           .fillAndStroke(colors.secondary, colors.primary);

        doc.fontSize(10)
           .fillColor(colors.white)
           .font('Helvetica-Bold')
           .text('GRADE DISTRIBUTION: ', leftMargin + 10, currentY + 12);

        let xPos = 180;
        Object.entries(gradeDistribution).forEach(([grade, count]) => {
          doc.fontSize(9)
             .fillColor(colors.white)
             .font('Helvetica')
             .text(`${grade}: ${count}`, xPos, currentY + 12);
          xPos += 80;
        });

        currentY += 40;
      }

      // Compact notes and recommendations
      if (!subjects || subjects.length === 0) {
        doc.rect(leftMargin, currentY, tableWidth, 25)
           .fillAndStroke(colors.warning, colors.primary);

        doc.fontSize(9)
           .fillColor(colors.white)
           .font('Helvetica-Bold')
           .text('📝 No marks available yet. Contact your teacher to add marks.', leftMargin + 10, currentY + 10);

        currentY += 35;
      }

    }

    // Compact Footer
    const footerY = doc.page.height - 30;
    doc.rect(0, footerY, doc.page.width, 30)
       .fill(colors.dark);
    
    doc.fontSize(8)
       .fillColor(colors.white)
       .font('Helvetica')
       .text('This is a computer generated document', 0, footerY + 12, { align: 'center' });

    doc.end();
  } catch (error) {
    console.error('Student PDF generation error:', error);
    res.status(500).json({ message: 'Error generating student PDF: ' + error.message });
  }
};

// 2. Class Report PDF - Enhanced with better spacing and layout
const generateClassReportPDF = (res, paper, students, filename) => {
  try {
    const doc = new PDFDocument({ 
      size: 'A4', 
      margin: 15,
      layout: 'landscape'
    });
    
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=${filename}`);
    doc.pipe(res);

    let y = 15;

    // Enhanced header with more space
    doc.rect(0, 0, doc.page.width, 80)
       .fillAndStroke('#1E40AF', '#1E40AF');
    
    // Main title - larger and more prominent
    doc.fontSize(24).fillColor('#FFFFFF').font('Helvetica-Bold')
       .text('EDUTRACK', 0, 20, { align: 'center' });
    
    // Subtitle with paper name - larger font
    doc.fontSize(14).fillColor('#E0E7FF').font('Helvetica')
       .text(`${paper.paper} - Internal Marks Report`, 0, 50, { align: 'center' });
    y = 100; // More space after header

    // Paper info with better spacing
    doc.fontSize(10).fillColor('black').font('Helvetica-Bold')
       .text(`Subject: ${paper.paper}`, 15, y)
       .text(`Department: ${paper.department}`, 15, y + 15)
       .text(`Total Students: ${students.length}`, 400, y)
       .text(`Generated: ${new Date().toLocaleDateString()}`, 400, y + 15);
    y += 45; // More space before table

    if (students && students.length > 0) {
      // Calculate row height with reasonable limits
      const headerHeight = 25;
      const footerHeight = 30;
      const statsHeight = 25;
      // Set a reasonable row height - minimum 18px, maximum 25px
      const rowHeight = Math.min(25, Math.max(18, Math.floor(400 / students.length))); // Cap at 25px per row
      
      // Table headers with better spacing
      doc.rect(15, y, 810, headerHeight).fillAndStroke('#1E40AF', '#000000');
      doc.fontSize(10).fillColor('white').font('Helvetica-Bold')
         .text('S.No', 20, y + 8)
         .text('Roll No', 60, y + 8)
         .text('Student Name', 140, y + 8)
         .text('Mid (30)', 280, y + 8)
         .text('Lab (10)', 340, y + 8)
         .text('Assign (10)', 390, y + 8)
         .text('Attend (10)', 450, y + 8)
         .text('Total (60)', 510, y + 8)
         .text('Grade', 570, y + 8)
         .text('Percentage', 620, y + 8)
         .text('Status', 700, y + 8);
      
      // Draw vertical lines in header with better positioning
      const colPositions = [55, 135, 275, 335, 385, 445, 505, 565, 615, 695];
      colPositions.forEach(pos => {
        doc.moveTo(pos, y).lineTo(pos, y + headerHeight).stroke('#FFFFFF');
      });
      
      y += headerHeight;

      // Student rows with enhanced spacing and readability
      students.forEach((student, i) => {
        const bg = i % 2 === 0 ? '#FFFFFF' : '#F8FAFC';
        doc.rect(15, y, 810, rowHeight).fillAndStroke(bg, '#E2E8F0');
        
        const total = student.total || 0;
        const grade = calculateGrade(total);
        const percentage = ((total / 60) * 100).toFixed(1);
        const status = total >= 36 ? 'PASS' : 'FAIL';
        
        // Grade-based color coding
        let gradeColor = '#000000';
        if (grade.includes('A')) gradeColor = '#10B981'; // Green
        else if (grade.includes('B')) gradeColor = '#3B82F6'; // Blue  
        else if (grade.includes('C')) gradeColor = '#F59E0B'; // Orange
        else if (grade.includes('F')) gradeColor = '#EF4444'; // Red
        
        // Status color
        const statusColor = status === 'PASS' ? '#10B981' : '#EF4444';
        
        const textY = y + Math.floor((rowHeight - 8) / 2); // Center text vertically
        
        doc.fontSize(9).fillColor('black').font('Helvetica')
           .text((i + 1).toString(), 25, textY)
           .text(student.rollNo || '', 60, textY)
           .text(student.name || '', 140, textY, { width: 130, ellipsis: true })
           .text((student.midMarks || 0).toString(), 290, textY)
           .text((student.lab || 0).toString(), 350, textY)
           .text((student.assignmentQuiz || 0).toString(), 400, textY)
           .text((student.attendance || 0).toString(), 460, textY)
           .text(total.toString(), 520, textY);
           
        // Grade with color
        doc.fillColor(gradeColor).font('Helvetica-Bold')
           .text(grade, 575, textY);
           
        // Percentage
        doc.fillColor('black').font('Helvetica')
           .text(`${percentage}%`, 625, textY);
           
        // Status with color
        doc.fillColor(statusColor).font('Helvetica-Bold')
           .text(status, 705, textY);
        
        // Draw vertical lines for each row
        colPositions.forEach(pos => {
          doc.moveTo(pos, y).lineTo(pos, y + rowHeight).stroke('#E2E8F0');
        });
        
        y += rowHeight;
      });

      // Enhanced statistics section
      y += 5;
      const avg = students.reduce((sum, s) => sum + (s.total || 0), 0) / students.length;
      const passed = students.filter(s => (s.total || 0) >= 36).length;
      const failed = students.length - passed;
      const passRate = (passed / students.length * 100).toFixed(1);
      const avgPercentage = ((avg / 60) * 100).toFixed(1);
      
      // Statistics background
      doc.rect(15, y, 810, 30).fillAndStroke('#8B5CF6', '#000000');
      
      // Statistics content in compact layout
      doc.fontSize(10).fillColor('white').font('Helvetica-Bold')
         .text('CLASS PERFORMANCE SUMMARY', 20, y + 5);
         
      doc.fontSize(8).fillColor('white').font('Helvetica')
         .text(`Students: ${students.length} | Average: ${avg.toFixed(1)}/60 (${avgPercentage}%) | Passed: ${passed} | Failed: ${failed} | Pass Rate: ${passRate}%`, 20, y + 18);
      
      // Draw vertical lines in statistics
      [145, 345, 445, 545, 645].forEach(pos => {
        doc.moveTo(pos, y).lineTo(pos, y + 30).stroke('#FFFFFF');
      });
      
      // Add grade distribution if space allows
      y += 35;
      if (y < doc.page.height - 60) {
        const gradeStats = {
          'A+/A': students.filter(s => (s.total || 0) >= 50).length,
          'B+/B': students.filter(s => (s.total || 0) >= 40 && (s.total || 0) < 50).length,
          'C': students.filter(s => (s.total || 0) >= 36 && (s.total || 0) < 40).length,
          'F': students.filter(s => (s.total || 0) < 36).length
        };
        
        doc.rect(15, y, 810, 25).fillAndStroke('#10B981', '#000000');
        doc.fontSize(10).fillColor('white').font('Helvetica-Bold')
           .text('GRADE DISTRIBUTION:', 20, y + 8);
           
        let xPos = 180;
        Object.entries(gradeStats).forEach(([grade, count]) => {
          doc.text(`${grade}: ${count}`, xPos, y + 8);
          xPos += 100;
        });
      }
    }

    doc.end();
  } catch (error) {
    console.error('PDF generation error:', error);
    res.status(500).json({ message: 'Error generating PDF: ' + error.message });
  }
};

// 3. Attendance Report PDF - Simplified version
const generateAttendanceReportPDF = (res, data, filename) => {
  try {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition', `attachment; filename=${filename}`);
    doc.pipe(res);

    // Simple header
    drawGradientRect(doc, 0, 0, doc.page.width, 80, colors.primary, colors.secondary);
    
    doc.fontSize(20)
       .fillColor(colors.white)
       .font('Helvetica-Bold')
       .text('📊 ATTENDANCE REPORT', 0, 25, { align: 'center' });

    // Report info
    let currentY = 100;
    doc.fontSize(14)
       .fillColor(colors.dark)
       .font('Helvetica-Bold')
       .text(`Subject: ${data.paper?.paper || 'N/A'}`, 50, currentY);

    doc.fontSize(12)
       .fillColor(colors.dark)
       .font('Helvetica')
       .text(`Section: ${data.section || 'N/A'}`, 50, currentY + 20)
       .text(`Total Classes: ${data.totalClasses || 0}`, 50, currentY + 40)
       .text(`Generated: ${new Date().toLocaleDateString()}`, 300, currentY + 20);

    currentY += 80;

    // Enhanced attendance table with better spacing
    if (data.students && data.students.length > 0) {
      // Calculate available space for better row distribution
      const availableHeight = doc.page.height - currentY - 150; // Reserve space for statistics
      const headerHeight = 30;
      const statsHeight = 80;
      const tableDataHeight = availableHeight - headerHeight - statsHeight;
      const rowHeight = Math.max(22, Math.floor(tableDataHeight / data.students.length)); // Minimum 22px per row
      
      // Enhanced headers with better spacing
      doc.fontSize(12)
         .fillColor(colors.white)
         .font('Helvetica-Bold');
      
      doc.rect(50, currentY, 500, headerHeight)
         .fillAndStroke(colors.primary, colors.dark);

      const textY = currentY + Math.floor((headerHeight - 12) / 2);
      doc.text('S.No', 60, textY)
         .text('Roll No', 100, textY)
         .text('Student Name', 160, textY)
         .text('Present', 280, textY)
         .text('Total', 320, textY)
         .text('Percentage', 360, textY)
         .text('Status', 440, textY);

      // Draw vertical lines in header
      const colPositions = [95, 155, 275, 315, 355, 435];
      colPositions.forEach(pos => {
        doc.moveTo(pos, currentY).lineTo(pos, currentY + headerHeight).stroke(colors.white);
      });

      currentY += headerHeight;

      // Enhanced data rows with better spacing
      data.students.forEach((student, index) => {
        const percentage = ((student.present || 0) / (data.totalClasses || 1) * 100);
        let status = 'EXCELLENT';
        let statusColor = colors.success;
        
        if (percentage >= 90) {
          status = 'EXCELLENT';
          statusColor = colors.success;
        } else if (percentage >= 75) {
          status = 'GOOD';
          statusColor = colors.secondary;
        } else if (percentage >= 50) {
          status = 'AVERAGE';
          statusColor = colors.warning;
        } else {
          status = 'POOR';
          statusColor = colors.danger;
        }
        
        const bgColor = index % 2 === 0 ? colors.white : colors.light;
        doc.rect(50, currentY, 500, rowHeight)
           .fillAndStroke(bgColor, colors.secondary);

        // Add status background highlight
        const statusBgColor = percentage >= 75 ? '#ECFDF5' : percentage >= 50 ? '#FEF3C7' : '#FEF2F2';
        doc.rect(435, currentY + 2, 110, rowHeight - 4)
           .fill(statusBgColor);

        const dataTextY = currentY + Math.floor((rowHeight - 10) / 2);
        
        doc.fontSize(10)
           .fillColor(colors.dark)
           .font('Helvetica')
           .text((index + 1).toString(), 60, dataTextY)
           .text(student.rollNo || 'N/A', 100, dataTextY)
           .text(student.name || 'N/A', 160, dataTextY, { width: 110, ellipsis: true })
           .text((student.present || 0).toString(), 285, dataTextY)
           .text((data.totalClasses || 0).toString(), 325, dataTextY)
           .text(`${percentage.toFixed(1)}%`, 365, dataTextY);

        doc.fillColor(statusColor)
           .font('Helvetica-Bold')
           .text(status, 445, dataTextY);

        // Draw vertical lines for each row
        colPositions.forEach(pos => {
          doc.moveTo(pos, currentY).lineTo(pos, currentY + rowHeight).stroke(colors.secondary);
        });

        currentY += rowHeight;
      });

      // Enhanced statistics section
      currentY += 20;
      const avgAttendance = data.students.reduce((sum, s) => sum + ((s.present || 0) / (data.totalClasses || 1) * 100), 0) / data.students.length;
      const excellentCount = data.students.filter(s => ((s.present || 0) / (data.totalClasses || 1) * 100) >= 90).length;
      const goodCount = data.students.filter(s => {
        const perc = ((s.present || 0) / (data.totalClasses || 1) * 100);
        return perc >= 75 && perc < 90;
      }).length;
      const averageCount = data.students.filter(s => {
        const perc = ((s.present || 0) / (data.totalClasses || 1) * 100);
        return perc >= 50 && perc < 75;
      }).length;
      const poorCount = data.students.filter(s => ((s.present || 0) / (data.totalClasses || 1) * 100) < 50).length;

      // Main statistics box
      doc.rect(50, currentY, 500, 80)
         .fillAndStroke(colors.accent, colors.primary);

      doc.fontSize(14)
         .fillColor(colors.white)
         .font('Helvetica-Bold')
         .text('ATTENDANCE STATISTICS', 60, currentY + 15);

      doc.fontSize(11)
         .fillColor(colors.white)
         .font('Helvetica')
         .text(`Class Average: ${avgAttendance.toFixed(1)}%`, 60, currentY + 35)
         .text(`Total Students: ${data.students.length}`, 60, currentY + 50)
         .text(`Total Classes: ${data.totalClasses || 0}`, 60, currentY + 65);

      doc.text(`Excellent (≥90%): ${excellentCount}`, 250, currentY + 35)
         .text(`Good (75-89%): ${goodCount}`, 250, currentY + 50)
         .text(`Average (50-74%): ${averageCount}`, 250, currentY + 65);

      doc.text(`Poor (<50%): ${poorCount}`, 400, currentY + 35)
         .text(`Above 75%: ${excellentCount + goodCount}`, 400, currentY + 50)
         .text(`Below 75%: ${averageCount + poorCount}`, 400, currentY + 65);

      currentY += 100;

      // Attendance distribution chart
      if (currentY < doc.page.height - 80) {
        doc.rect(50, currentY, 500, 50)
           .fillAndStroke(colors.secondary, colors.primary);

        doc.fontSize(12)
           .fillColor(colors.white)
           .font('Helvetica-Bold')
           .text('ATTENDANCE DISTRIBUTION', 60, currentY + 10);

        // Visual representation with bars
        const barWidth = 80;
        const maxCount = Math.max(excellentCount, goodCount, averageCount, poorCount);
        
        if (maxCount > 0) {
          const categories = [
            { label: 'Excellent', count: excellentCount, color: colors.success },
            { label: 'Good', count: goodCount, color: colors.secondary },
            { label: 'Average', count: averageCount, color: colors.warning },
            { label: 'Poor', count: poorCount, color: colors.danger }
          ];

          let barX = 80;
          categories.forEach(cat => {
            const barHeight = (cat.count / maxCount) * 20;
            doc.rect(barX, currentY + 35 - barHeight, 15, barHeight)
               .fill(cat.color);
            
            doc.fontSize(8)
               .fillColor(colors.white)
               .font('Helvetica')
               .text(cat.label, barX - 5, currentY + 38)
               .text(cat.count.toString(), barX + 2, currentY + 25);
            
            barX += 100;
          });
        }
      }
    }

    // Footer
    const footerY = doc.page.height - 50;
    doc.rect(0, footerY, doc.page.width, 50)
       .fill(colors.dark);
    
    doc.fontSize(10)
       .fillColor(colors.white)
       .font('Helvetica')
       .text('Generated by EDUTRACK Educational Management System', 0, footerY + 20, { align: 'center' });

    doc.end();
  } catch (error) {
    console.error('Attendance PDF generation error:', error);
    res.status(500).json({ message: 'Error generating attendance PDF: ' + error.message });
  }
};

// Helper function to calculate grade
const calculateGrade = (totalMarks) => {
  const marks = totalMarks || 0;
  if (marks >= 55 && marks <= 60) return "A+";
  else if (marks >= 50 && marks <= 54) return "A";
  else if (marks >= 45 && marks <= 49) return "B+";
  else if (marks >= 40 && marks <= 44) return "B";
  else if (marks >= 36 && marks <= 39) return "C";
  else return "F";
};

module.exports = {
  colors,
  drawGradientRect,
  createProfessionalHeader,
  createProfessionalFooter,
  createInfoBox,
  createColorfulTable,
  createStatisticsBoxes,
  generateStudentReportPDF,
  generateClassReportPDF,
  generateAttendanceReportPDF,
  calculateGrade
};