const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

// Helper function to format currency with Rs.
const formatCurrency = (amount) => {
  return `Rs. ${amount.toLocaleString('en-IN', { 
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
    useGrouping: true
  })}`;
};

const generateSalaryReportPDF = async (reportData) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      
      // Create reports directory if it doesn't exist
      const reportsDir = path.join('/tmp/uploads/reports');
      if (!fs.existsSync(reportsDir)) {
        fs.mkdirSync(reportsDir, { recursive: true });
      }
      
      const filename = `salary_report_${Date.now()}.pdf`;
      const filepath = path.join(reportsDir, filename);
      
      // Pipe PDF to file
      const stream = fs.createWriteStream(filepath);
      doc.pipe(stream);

      // Header with EDUTRACK branding
      doc.fontSize(24)
         .fillColor('#FF6B35')
         .text('EDUTRACK', 50, 50, { align: 'center' });

      doc.fontSize(12)
         .fillColor('#666666')
         .text('Educational Management System', 50, 80, { align: 'center' });

      // Title
      doc.fontSize(18)
         .fillColor('#000000')
         .text(reportData.title, 50, 120, { align: 'center' });

      doc.fontSize(12)
         .text(`Generated on: ${reportData.generatedDate}`, 50, 150, { align: 'center' });

      // Orange line separator
      doc.strokeColor('#FF6B35')
         .lineWidth(2)
         .moveTo(50, 180)
         .lineTo(550, 180)
         .stroke();

      // Summary section
      let yPosition = 210;
      
      doc.rect(50, yPosition, 500, 80)
         .fillAndStroke('#f8f9fa', '#e9ecef');

      doc.fillColor('#000000')
         .fontSize(14)
         .text('Summary Statistics', 60, yPosition + 10, { underline: true });

      doc.fontSize(12)
         .text(`Total Staff: ${reportData.summary.totalStaff}`, 60, yPosition + 35)
         .text(`Total Payroll: ${formatCurrency(reportData.summary.totalPayroll)}`, 200, yPosition + 35)
         .text(`Average Salary: ${formatCurrency(reportData.summary.averageSalary)}`, 380, yPosition + 35);

      yPosition += 100;

      // Table header
      const tableTop = yPosition;
      const tableHeaders = ['Employee ID', 'Name', 'Department', 'Role', 'Salary Type', 'Base Salary'];
      const columnWidths = [70, 100, 80, 60, 80, 80];
      let xPosition = 50;

      // Draw table header background
      doc.rect(50, tableTop, 500, 25)
         .fillAndStroke('#FF6B35', '#FF6B35');

      // Header text
      doc.fillColor('#FFFFFF')
         .fontSize(10);

      tableHeaders.forEach((header, i) => {
        doc.text(header, xPosition + 5, tableTop + 8, { 
          width: columnWidths[i] - 10, 
          align: 'left' 
        });
        xPosition += columnWidths[i];
      });

      yPosition = tableTop + 25;

      // Table rows
      doc.fillColor('#000000');
      reportData.staffData.forEach((staff, index) => {
        // Alternate row colors
        if (index % 2 === 0) {
          doc.rect(50, yPosition, 500, 20)
             .fillAndStroke('#f9f9f9', '#ddd');
        } else {
          doc.rect(50, yPosition, 500, 20)
             .stroke('#ddd');
        }

        doc.fillColor('#000000');
        xPosition = 50;

        const rowData = [
          staff.employeeId,
          staff.name,
          staff.department,
          staff.role,
          staff.salaryType,
          formatCurrency(staff.baseSalary)
        ];

        rowData.forEach((data, i) => {
          doc.text(data, xPosition + 5, yPosition + 5, { 
            width: columnWidths[i] - 10, 
            align: 'left',
            height: 15
          });
          xPosition += columnWidths[i];
        });

        yPosition += 20;

        // Add new page if needed
        if (yPosition > 700) {
          doc.addPage();
          yPosition = 50;
        }
      });

      // Footer
      yPosition += 30;
      doc.strokeColor('#ddd')
         .lineWidth(1)
         .moveTo(50, yPosition)
         .lineTo(550, yPosition)
         .stroke();

      doc.fontSize(10)
         .fillColor('#666666')
         .text('This report was generated by EDUTRACK Educational Management System', 50, yPosition + 15, { align: 'center' })
         .text(`© ${new Date().getFullYear()} EDUTRACK - All Rights Reserved`, 50, yPosition + 30, { align: 'center' });

      // Finalize PDF
      doc.end();

      stream.on('finish', () => {
        resolve({
          success: true,
          filename,
          filepath
        });
      });

      stream.on('error', (error) => {
        reject(error);
      });

    } catch (error) {
      reject(error);
    }
  });
};

module.exports = {
  generateSalaryReportPDF
};